services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - trustpay_network
    env_file:
      - ./backend/.env  # Load variables from backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - trustpay_network
    # env_file:
    #   - ./frontend/.env  # Uncomment if frontend needs env variables

  mongodb:
    image: mongo:6.0  # Specify an exact version instead of latest
    ports:
      - "27017:27017"
    networks:
      - trustpay_network
    volumes:
      - mongo-data:/data/db  

networks:
  trustpay_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
