services:
  backend:
    build: ./backend
    ports:
      - "3000:3000" 
    networks:
      - trustpay_network
    environment:
      MONGO_URI: mongodb+srv://mukulbhatia189:mukulbhatia189@cluster0.zg7kjju.mongodb.net/  
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - trustpay_network
    # environment:
    #   REACT_APP_API_URL: http://backend:3000 

  mongodb:
    image: mongo:latest   # try to give exact version instead of latest.
    ports:
      - "27017:27017"  
    networks:
      - trustpay_network
    volumes:
      - mongo-data:/data/db  

networks:
  trustpay_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally